name: Docker Build and Publish
env:
  DOCKERHUB_IMAGE: broadlinkac/broadlink_ac_mqtt
  DOCKERHUB_LINK: https://hub.docker.com/r/broadlinkac/broadlink_ac_mqtt/tags/
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: broadlinkac/broadlink_ac_mqtt
        tag_with_ref: true
        tag_with_sha: true
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Send status to Discord
        uses: 8398a7/action-slack@v3
        with:
          author_name: Docker build and publish
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo,message,commit,action
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
          SLACK_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
